language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
env:
  global:
  - secure: czAfRgLwP7Owth8c7ofrixpTJ4XKj67d3BjCne+uxfKGFrqEWDgCvv0oyiCzRA3EVXwnnadX1rCWJTZiX+7Py+ifyp8OzSJWztOE9//En6TL4Ps0NQis35Fod5TRRxzKHvDqnKHmXXila/qekazn6U+VqRQo1Fqynlw2OF/KtvsZn5PeDxIPRjs237oCfyaw6jFB5FBXfUYIGOVhWgLwJxsX7Oj4tQIj2fmzKUSFEVTi574RMiCUkqSnkdKpOFv881A8HwSijQqWKqA3zQXkCju+RxLGvgjKT4Xh3WkRIWW4h2TUiGPT4ixk2oHv8omDDZp+y+upzVKu2GyG6VjJ4uiuHrCJZpZwjgA44Mzkvxzb4rM8jDHqufQ+BHAa9nUHd2xMoHn+O3cx2HPdXz7LfNSGgrnk0StoAedf/IAdn/ceYd1RHZSSMz/TqOeFgKu6kkNwZVU5mBhWtpxNDdFVx+JWh6v8myvk2D1TGm1xjyKjJ1IdeaN7o9Y4Vg7FX1x7RbFHF2f36SZmfvJztYtTQscv+m0uhLiQK/5Zoi5SpziPpYyL9EVqrg0ZEuQHoLECgWny+ShVk7ZXA66YHsb4qHbVtwE75TTICaEsycK3lRbwLy2+fW432ySTzxzXTpjyNSAcKo0TGCY9QdSyFLOUFpocMYzcCDfPX6wO2LNQmU8=
  - secure: FD638Mprl4oGKMnmPMZDkMTpIhIdjd8DyTiNo632TvxfjOeowxobzhEhz56fA+UwhVXKBT9bRfZWuThIS4wncDKsaFIC0efea9Ii7BHlL/HUoNcVNNmbldI9t8K0d6AqNcSIYExx+p7aIZ9Uk2lJpscTiyBc2Vn2VpGQ2JNOZDtPu8RXqth2+QEfQ7aSWax4oIjWSJFFRcMDOTzuH/k8oehfTiaB02OWgfrjDHcwtaH+j91cseKdPgauusFCvRk1r2rt3FHARraF5ILJTLkzz/Wll0XlYqQ/Nn6z/2mfzRP2cB4S9aGlsbKldcDLRKo3W1ofVJ1lvLzNu/VTwxL2prJ97RExLIdob7xtTWolg1TWJ+yXTR+Mg1spPHMKpiHVTwHOpqPNaxFsgBIjj1xif0OVS/2pEQ6feFUCbD5CP6vPsW8iQTv3KJiekUWevGYAlsKJ12JE/oxhydkyiHZpEjpSXyNHZhx5Id7KAnFqLCrJFnorZwKOvXSItPqLNXr2tCVy5qrLhhK3eUyyT9Qsj4z2hzzmLgoZKaQ4Dsc7Xcf9fTcLPKsEt2y7ZMghLLAvu/V/ddZ61aTGg84lAAsJtI8Mb61+gzDhnmhS3YwPoMlIuxiMvX9I8WNUQJ2ZCPNlKsy7ANHtD09vU39ISe/MMMha/DUK9PyAHudQVbM2b04=
notifications:
  slack:
    rooms:
      secure: mdmFG215oK7eXqkJ0Ndq5g8Lgk8nS5v5pQzpuABvkeeq0sbNZHErpFsR4wivEy5pU1dcqffmHiPfVNRCO8oU5kJ6gsJlfNLo0HqdN0peZOlQXS8+vFjOLQfUHWcOpCU/mG4Mol5h07DfW+19AJVYwwCEr3pqnfjSlbSISfOHTFPQGm3xh7sN6y+wOWarUCxkkSYG0E5c3Yx06JXA4IG7N55FQUffbVVBKO+jBg9Qj6wRgmWhWwfd8YV0T3PD7zQhlfd/SQEpbn6Z4diDpAQxxa1MTt9pGd6s6lLhIrqyFX5YclRPZj+7B06cjTPK7mwAiZ62CmiVoCmVHiw/IXpAfx6QP41XpKAKGmDEhx6HL9kD577wN0DKp41cOK2F5f2ZCg59yP4IWn553855+lVNdbde4pNXfx+YZLiEJ1CSjc7cn2C4xqz2qZ/7CkjvbWNDaFd3ms0zmETNu5PrQfVp/6jBtnsHmUfQg7ROGM1p1BcO6rEJnlogzjK+9tZse32+a5uFHiiqUMy8cIwitRAeePC3mee5l+dTmtGgZ8GEOyOLbr6dSbj5O27IAYpjTLcfrKqnFhtIO54ehtkYWMHhOjWtnCGbPGWsIdHGN1fOeP6e/hbU+sktaGV7K3706LHqamSUHsENa7O7cUijZR5X3X47vSvJ2+qn+U6CE0YuPDU=
    on_success: change
    on_failure: always
